services:
  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "5001:5000"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"  # Expose port 443 for HTTPS
    depends_on:
      - flask_app
